name: Nuclei-Templates-Collector

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install tools & nucleihub + nuclei
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y tar unzip curl

          # nucleihub (v0.0.3)
          wget -q https://github.com/rix4uni/nucleihub/releases/download/v0.0.3/nucleihub-linux-amd64-0.0.3.tgz
          tar -xzf nucleihub-linux-amd64-0.0.3.tgz
          sudo mv nucleihub /usr/local/bin/nucleihub
          rm -f nucleihub-linux-amd64-0.0.3.tgz

          # nuclei (mặc định 3.4.x; có thể ghim qua env NUCLEI_VERSION)
          NUCLEI_VERSION="${NUCLEI_VERSION:-3.4.7}"
          wget -q -P /tmp "https://github.com/projectdiscovery/nuclei/releases/download/v${NUCLEI_VERSION}/nuclei_${NUCLEI_VERSION}_linux_amd64.zip"
          unzip -q /tmp/nuclei_${NUCLEI_VERSION}_linux_amd64.zip -d /tmp/nuclei
          sudo mv /tmp/nuclei/nuclei /usr/local/bin/nuclei
          rm -rf /tmp/nuclei /tmp/nuclei_${NUCLEI_VERSION}_linux_amd64.zip
          nuclei -version

      - name: Build combined repo list (nucleihub + Emad README.txt)
        env:
          NUCLEIHUB_LIST: https://raw.githubusercontent.com/rix4uni/nucleihub/refs/heads/main/reponames.txt
          EMAD_LIST: https://raw.githubusercontent.com/emadshanab/Nuclei-Templates-Collection/refs/heads/main/README.txt
        run: |
          set -euo pipefail
          mkdir -p lists

          # Repos "Updated today" từ nucleihub
          curl -fsSL "$NUCLEIHUB_LIST" \
            | nucleihub updatecheck \
            | awk '/^Updated today: /{sub(/^Updated today: /,"");print}' \
            > lists/nucleihub-updated.txt

          # Tất cả link GitHub từ README.txt của Emad
          curl -fsSL "$EMAD_LIST" \
            | grep -Eo 'https://github.com/[A-Za-z0-9._-]+/[A-Za-z0-9._-]+' \
            | sort -u \
            > lists/emad.txt

          # Hợp nhất & loại trùng theo URL
          cat lists/nucleihub-updated.txt lists/emad.txt \
            | sort -u > lists/combined.txt

          echo "Counts:"
          wc -l lists/*.txt || true

      - name: Download repositories with nucleihub
        run: |
          set -euo pipefail
          rm -rf nucleihub-downloaded-repos nucleihub-templates
          mkdir -p nucleihub-downloaded-repos nucleihub-templates

          # Tải các repo trong danh sách
          if [ -s lists/combined.txt ]; then
            cat lists/combined.txt \
              | nucleihub download --output-directory nucleihub-downloaded-repos
          else
            echo "No repositories to download today."
          fi

          # Khử trùng lặp & hợp nhất về thư mục 'nucleihub-templates'
          nucleihub duplicate \
            --input-directory nucleihub-downloaded-repos \
            --output-directory nucleihub-templates \
            --large-content

          # Xoá bản tải thô
          rm -rf nucleihub-downloaded-repos

      - name: Validate templates with nuclei
        run: |
          # Kiểm tra lỗi cú pháp template; không fail job nếu có cảnh báo
          set -e
          nuclei -validate -t nucleihub-templates || true

      - name: Commit and push changes if there are any
        run: |
          set -euo pipefail
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add -A
          if ! git diff --cached --quiet; then
            IST_DATE=$(TZ='Asia/Kolkata' date +'%a %b %d %H:%M:%S IST %Y')
            git commit -m "Updated templates (dedup via nucleihub): $IST_DATE"
            git push
          else
            echo "No changes to commit"
          fi
